---
- hosts: localhost
  tasks:
  - name: create launch config
    ec2_lc:
      name: my_new_lc
      image_id: ami-0f7919c33c90f5b58
      key_name: MyMac
      region: us-east-2
      security_groups: sg-0517606b76b40a586
      instance_type: t2.micro
      assign_public_ip: yes

  - ec2_asg:
      name: myasg
      launch_config_name: my_new_lc
      health_check_period: 10
      health_check_type: EC2
      replace_all_instances: yes
      min_size: 2
      max_size: 5
      desired_capacity: 3
      region: us-east-2



  - name: Installs wordpress
    become: yes
    become_method: sudo
    user: centos
    tasks:
      - name: Install epel-release
        shell: "sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y"
        ignore_errors: true
      - name: config manager enabled
        shell: "sudo yum-config-manager --enable remi-php72"
        ignore_errors: true
      - name: Install necessary packages
        package:
          name: "{{item}}"
          state: latest
        with_items:
        - epel-release
        - wget
        - unzip
        - mariadb-server
        - httpd
        - php
        - php-common
        - php-opcache
        - php-mcrypt
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
        - mysql
        ignore_errors: true
      - name: Download wordpress Package
        get_url:
          url: https://wordpress.org/wordpress-5.2.1.tar.gz
          dest: /tmp/
        ignore_errors: true
      - name: Unzip wordpres file
        unarchive:
          src: "/tmp/wordpress-5.2.1.tar.gz"
          dest: "/var/www/html"
          remote_src: yes
        ignore_errors: true
      - name: Move files to html folder
        shell: "mv /var/www/html/wordpress/* /var/www/html"
        become: yes
        become_method: sudo
        ignore_errors: yes
      - name: Restart httpd
        systemd:
          name: httpd
          state: restarted
          enabled: yes




  # - ec2_asg:
  #     name: asg
  #     availability_zones: [ 'us-east-2a', 'us-east-2b', 'us-east-2c' ]
  #     launch_config_name: 'lc-1'
  #     min_size: 2
  #     max_size: 5
  #     desired_capacity: 3
  #     vpc_zone_identifier: [ 'subnet-03fbda95337389bf6', 'subnet-06b304c4f160172fe', 'subnet-05370a8b90da8db50' ]
  #     tags:
  #         propagate_at_launch: yes

