---
- hosts: localhost
  become: yes
  become_method: sudo
  vars_files: 
  - some_region.yaml
  tasks: 
  - name: Say hello
    package:
      name: "{{package_name}}"
      state: "{{state}}"


      #ansible-playbook input.yaml --extra-vars "package_name=telnet" --extra-vars="state=installed"