---
- name: My First playbook
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - name: Install package
    package:
      name: httpd
      state: installed


  - name: Install telnet
    package:
      name: telnet
      state: installed

  - name: Add Bob
    package:
      name: telnet
      state: Present