---
- name: Start services
  hosts: all #DB
  become: true
  become_method: sudo
  user: centos
  ignore_errors: true       #Don't stop if there are errors
  tasks:
  - name: Stop r1soft CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    systemd:
      name: sbm-agent
      state: started
    ignore_errors: true


  - name: Stop r1soft on CentOS 6
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
    system:
      name: cdp-server
      state: started
    ignore_errors: true    


  - name: Stop Filebeat 
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") 
    systemd:
      name: sbm-agent
      state: started
    ignore_errors: true


  - name: Stop NRPE
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    systemd:
      name: sbm-agent
      state: started
    ignore_errors: true


  - name: Stop MariaDB
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    systemd:
      name: mariadb
      state: started
    ignore_errors: true
      